# -*- coding: utf-8 -*-
"""Paraphraser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkkQyYWAE2z-U53maLIAksqRVtg1bPfq
"""

!pip install --upgrade pip
!pip install transformers
!pip install sentencepiece
!pip install transformers[sentencepiece]

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
class Paraphraser:
  def __init__(self):
    self.tokenizer = AutoTokenizer.from_pretrained("Vamsi/T5_Paraphrase_Paws")  
    self.model = AutoModelForSeq2SeqLM.from_pretrained("Vamsi/T5_Paraphrase_Paws")
  
  def inference(self, sent):
    text =  "paraphrase: " + sent + " </s>"
    encoding = self.tokenizer.encode_plus(text,padding='max_length', return_tensors="pt")
    input_ids, attention_masks = encoding["input_ids"], encoding["attention_mask"]
    outputs = self.model.generate(
        input_ids=input_ids, attention_mask=attention_masks,
        max_length=256,
        do_sample=True,
        top_k=120,
        top_p=0.95,
        early_stopping=True,
        num_return_sequences=10
    )
    return [self.tokenizer.decode(output, skip_special_tokens=True,clean_up_tokenization_spaces=True) for output in outputs ]

example = Paraphraser()
sent = "can u tell me whats wrong in it"
for output in example.inference(sent):
    print(output)

